spring.application.name=faldren-backend

server.port=8080


# ===============================
# SUPABASE POSTGRESQL
# ===============================

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require

spring.datasource.username=${SUPABASE_DB_USERNAME}

spring.datasource.password=${SUPABASE_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================

app.jwt.secret=${JWT_SECRET}

# 24 hours
app.jwt.expiration=86400000


# ===============================
# FALDREN ADMIN
# ===============================

app.admin.name=${FALDREN_ADMIN_NAME}
app.admin.email=${FALDREN_ADMIN_EMAIL}
app.admin.password=${FALDREN_ADMIN_PASSWORD}
# ===============================
# EMAIL / SMTP
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.starttls.required=true

# =====================================
# FALDREN NOTIFICATION MAIL
# =====================================

app.notification-mail.username=${NOTIFICATION_MAIL_USERNAME}
app.notification-mail.password=${NOTIFICATION_MAIL_APP_PASSWORD}

app.admin.notification-email=${FALDREN_ADMIN_NOTIFICATION_EMAIL}

app.frontend.url=${FRONTEND_URL:http://localhost:5173}